const Portfolio_data = [
  {
    id: 1,
    title: "Eat Express",
    imgURL: "/images/eatxpress.png",
    content:
      "Eat Express is a robust backend system for restaurant management and delivery logistics. The platform boasts real-time tracking, AI-driven recommendations, and a secure payment gateway, ensuring a superior and secure user experience. Eat Express stands  as a testament to Kuvaka s prowess in crafting bespoke IT solutions that redefine industry standards and elevate user satisfaction. With its technical sophistication and user-centric design, Eat Express positions Kuvaka as a key player in revolutionizing the digital food delivery landscape",
    technologies: [
      "NodeJs",
      "NextJS",
      "MongoDB",
      "Prisma",
      "ExpressJs",
      "Git",
      "Flutter",
      "Stripe",
      "AWS",
      "Google Cloud",
      "React Native",
      "Navigation API",
      "Routing API",
    ],
  },
  {
    id: 2,
    title: "Fossip",
    imgURL: "/images/fossip.png",
    content: `Fossip is a Restaurant Management Software that helps restaurant owners to manage their orders, inventory, and staff. The application is available on Web, Android and IOS.`,
    technologies: ["NextJS", "Flutter", "NodeJs", "MongoDB"],
  },
  {
    id: 3,
    title: "chargeERP",
    imgURL: "/images/chargeERP.png",
    content: `ChargeERP is a SAAS Platform for the Fintech Industry offering Payment Solutions for Commercial Transport Industry & Corporates through prepaid loadable Rupay cards. Companies can manage fleet expenses, toll expenses, fuel expenses and lending to transport companies.`,
    technologies: ["Next JS", "MongoDB", "Prisma", "NodeJs"],
  },
  {
    id: 4,
    title: "xPay+",
    imgURL: "/images/xpay.png",
    content: `xPay+ is a Fintech SAAS Platform offering Payment Solutions for Commercial Transport Industry & Corporates through prepaid loadable Rupay cards. Companies can manage fleet expenses, toll expenses, fuel expenses and lending to transport companies.`,
    technologies: [
      "Next JS",
      "Next sssJS",
      "Next JS",
      "Next JS",
      "Next JS",
      "Next sssJS",
      "Next JS",
      "Next JS",
      "Next JS",
      "Next sssJS",
      "Next JS",
      "Next JS",
    ],
  },
  {
    id: 5,
    title: "Viosa",
    imgURL: "/images/viosa.png",
    content: `Edtech Platform is the first unified technology platform that coaches students in acquiring sector-based competencies, helps them build their professional profiles, & guides them to achieve their aspirational employment through video courses, MCQ tests etc. The platform also has automated mock interviews where the users can practice in a real time interview environment with a real human like bot interviewer. Users can also create resumes in the easiest way possible with the help of AI powered by ChatGPT.`,
    technologies: ["Next JS", "MongoDB", "Prisma", "NodeJs"],
  },
  {
    id: 6,
    title: "SaverIt",
    imgURL: "/images/saverit.png",
    content: `It is a Mobile based restaurants commerce platform for restaurants to sell their surplus food prepared daily where customers can avail heavy discounts during the mentioned time period.`,
    technologies: ["Next JS", "Next sssJS", "Next JS", "Next JS"],
  },
  {
    id: 7,
    title: "Billberry",
    imgURL: "/images/billberry.png",
    content: `It is a restaurant management software for users to track orders of different outlets, and analytical performance on different metrics. The application is available on Web, Android and IOS.    `,
    technologies: ["Next JS", "MongoDB", "Prisma", "NodeJs"],
  },
  {
    id: 8,
    title: "Joya",
    imgURL: "/images/joya.png",
    content: `Joya is one of the top companies in baby food products in Thailand selling D2C through their website and getting the customers onboarded for their subscriptions.`,
    technologies: ["Next JS", "Next sssJS", "Next JS", "Next JS"],
  },
  {
    id: 9,
    title: "Panwari",
    imgURL: "/images/panwari.png",
    content: `It is a B2B e-commerce mobile application that allows effortless onboarding of vendors and buyers on the platform. With simple and uncluttered navigation, the app brings together multiple vendors and consolidates their offerings under the same hood especially for paan shops.`,
    technologies: ["Next JS", "MongoDB", "Prisma", "NodeJs"],
  },
  {
    id: 10,
    title: "Loop ERP",
    imgURL: "/images/looperp.png",
    content: `Loop ERP App is designed to solve the challenges of Retail, Distribution and Manufacturing business that keep entrepreneurs tied to their desks. Loop ERP has been designed for Apparel and Footwear, FMCG, F&B, Electronics & Telecommunication and Pharmaceutical businesses that need complete visibility over their entire organisational structure.`,
    technologies: ["Next JS", "MongoDB", "Prisma", "NodeJs"],
  },
  {
    id: 11,
    title: "Red Carpet",
    imgURL: "/images/redcarpet.png",
    content: `RedCarpet lends to customers in India . There are less than 50 million credit cards for almost a billion people in India.... because there is no data, no widespread credit bureaus to profile and score customers. RedCarpet gathers alternative data ethically and responsibly . We use this data to give access to credit line cards to users who never had any access to credit before.`,
    technologies: ["Next JS", "MongoDB", "Prisma", "NodeJs"],
  },
  {
    id: 12,
    title: "CafeYoda",
    imgURL: "/images/cafeyoda.png",
    content:
      "Cafe Yoda a paradise for coffee lovers and NFT enthusiasts. Our team helped with everything from website development to smart contract implementation, custom blockchain integration, and wallet linking. We also provided blockchain consulting services to guide Cafe Yoda through the product launch, marketing, and community building phases",
    technologies: [
      "React",
      "Solidity",
      "Web3.js",
      "ERC720",
      "Git",
      "Google Cloud",
      "Blender",
    ],
  },
];
export default Portfolio_data;
